FROM oven/bun:1

WORKDIR /usr/src/app



COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install

RUN bun run db:generate

ARG DATABASE_URL 
# This is an arguement which has to be passed while running docker build -t web-fe for connecting to the db 

ENV DATABASE_URL=$DATABASE_URL

RUN apt-get update -y && apt-get install -y openssl


RUN bun run build

EXPOSE 3000

CMD [ "bun","run","start:web" ]