# name : Deploy the websocket 

# on: 
#   push: 
#     branches:[ main ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       -name: Checkout the code 
#       uses: actions/checkout@v2

#       -name: Docker Login 
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#       -name: Build and push 
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         file: ./Docker/Dockerfile.websocket
#         push: true
#         tags: Krishcodesw/user-app-websocket:${{ github.sha }}
name: Deploy the websocket

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.websocket
          push: true
          tags: krishcodesw/user-app-websocket:${{ github.sha }}

      - name: Deploy to VM 
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostkeyChecking=no -i ~/ssh_key ubuntu@16.171.255.148 -t "docker stop user_websocket && docker run --name user-app-websocket -d -p 8081:8081 krishcodesw/user-app-websocket:${{ github.sha }}"

