# name : Deploy the websocket 

# on: 
#   push: 
#     branches:[ main ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       -name: Checkout the code 
#       uses: actions/checkout@v2

#       -name: Docker Login 
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#       -name: Build and push 
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         file: ./Docker/Dockerfile.websocket
#         push: true
#         tags: Krishcodesw/user-app-websocket:${{ github.sha }}
name: Deploy the websocket

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.websocket
          push: true
          tags: krishcodesw/user-app-websocket:${{ github.sha }}

